
import type { Player, Stats, Position } from './types';
import { Position as P } from './types';

export const POSITIONS: Position[] = [P.QB, P.RB, P.WR, P.TE, P.K, P.DST];

export const calculateFantasyPoints = (stats: Stats, position: Position, gamesPlayed: number): number => {
    let points = 0;
    if (!stats) return 0;

    // Standard PPR scoring
    points += (stats.passingYards ?? 0) * 0.04;
    points += (stats.passingTds ?? 0) * 4;
    points += (stats.interceptions ?? 0) * -2;
    points += (stats.rushingYards ?? 0) * 0.1;
    points += (stats.rushingTds ?? 0) * 6;
    points += (stats.receptions ?? 0) * 1; // PPR
    points += (stats.receivingYards ?? 0) * 0.1;
    points += (stats.receivingTds ?? 0) * 6;
    points += (stats.fumblesLost ?? 0) * -2;

    // Kicker scoring
    points += (stats.fieldGoalsMade0to39 ?? 0) * 3;
    points += (stats.fieldGoalsMade40to49 ?? 0) * 4;
    points += (stats.fieldGoalsMade50plus ?? 0) * 5;
    points += (stats.extraPointsMade ?? 0) * 1;

    // DST scoring
    points += (stats.sacks ?? 0) * 1;
    points += (stats.defensiveInterceptions ?? 0) * 2;
    points += (stats.fumblesRecovered ?? 0) * 2;
    points += (stats.safeties ?? 0) * 2;
    points += (stats.defensiveTds ?? 0) * 6;
    points += (stats.blockedKicks ?? 0) * 2;
    
    // Points allowed logic for DST (example scale)
    const pointsAllowed = stats.pointsAllowed;
    if (pointsAllowed !== undefined && position === P.DST) {
        if (pointsAllowed === 0) points += 10;
        else if (pointsAllowed <= 6) points += 7;
        else if (pointsAllowed <= 13) points += 4;
        else if (pointsAllowed <= 20) points += 1;
        else if (pointsAllowed <= 27) points += 0;
        else if (pointsAllowed <= 34) points += -1;
        else points += -4;
    }

    return parseFloat(points.toFixed(2));
};

export const INITIAL_PLAYERS: Player[] = [
    // San Francisco 49ers
    { id: 1, name: "Christian McCaffrey", position: P.RB, team: "SF", byeWeek: 9, tier: 1, adp: 1, espnRank: 1, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 15, gamesPlayed2024: 16, stats2024: { rushingYards: 1459, rushingTds: 14, receptions: 67, receivingYards: 564, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1300, rushingTds: 12, receptions: 65, receivingYards: 550, receivingTds: 6 }, espnPpgProjected: 21.0, sleeperPpgProjected: 21.8, notes: "The consensus #1 overall pick in a high-powered offense.", archetype: "Elite All-Purpose Back", projectionModifiers: { catalysts: ["Focal point of elite offense", "High-value touches (receptions + goal line)"], concerns: ["Slight injury risk from massive workload"] } },
    { id: 2, name: "Brock Purdy", position: P.QB, team: "SF", byeWeek: 9, tier: 6, adp: 85, espnRank: 90, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 15, gamesPlayed2024: 16, stats2024: { passingYards: 4280, passingTds: 31, interceptions: 11, rushingYards: 144, rushingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4300, passingTds: 30, interceptions: 12, rushingYards: 150, rushingTds: 2 }, espnPpgProjected: 18.5, sleeperPpgProjected: 18.8, archetype: "System QB", notes: "Efficient QB surrounded by elite weapons." },
    { id: 3, name: "Brandon Aiyuk", position: P.WR, team: "SF", byeWeek: 9, tier: 4, adp: 28, espnRank: 26, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 14, gamesPlayed2024: 16, stats2024: { receptions: 75, receivingYards: 1342, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 78, receivingYards: 1300, receivingTds: 7 }, espnPpgProjected: 15.2, sleeperPpgProjected: 15.9, archetype: "Elite Route Runner" },
    { id: 4, name: "Deebo Samuel", position: P.WR, team: "SF", byeWeek: 9, tier: 5, adp: 35, espnRank: 38, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 14, gamesPlayed2024: 15, stats2024: { receptions: 60, receivingYards: 892, receivingTds: 7, rushingYards: 225, rushingTds: 5 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 62, receivingYards: 900, receivingTds: 6, rushingYards: 200, rushingTds: 4 }, espnPpgProjected: 14.8, sleeperPpgProjected: 15.1, archetype: "Hybrid 'Wide-back'" },
    { id: 5, name: "George Kittle", position: P.TE, team: "SF", byeWeek: 9, tier: 5, adp: 55, espnRank: 58, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 13, gamesPlayed2024: 16, stats2024: { receptions: 65, receivingYards: 1020, receivingTds: 6 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 68, receivingYards: 950, receivingTds: 6 }, espnPpgProjected: 11.5, sleeperPpgProjected: 12.0, archetype: "YAC Monster TE" },

    // New York Jets
    { id: 6, name: "Breece Hall", position: P.RB, team: "NYJ", byeWeek: 12, tier: 1, adp: 4, espnRank: 3, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 20, gamesPlayed2024: 17, stats2024: { rushingYards: 994, rushingTds: 5, receptions: 76, receivingYards: 591, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { rushingYards: 1150, rushingTds: 8, receptions: 85, receivingYards: 700, receivingTds: 5 }, espnPpgProjected: 19.2, sleeperPpgProjected: 20.0, notes: "Explosive dual-threat back, set to benefit from Aaron Rodgers' return.", archetype: "Dual-Threat RB1", projectionModifiers: { catalysts: ["Massive QB upgrade", "Elite receiving role for an RB"], concerns: ["Tough division defenses"] } },
    { id: 7, name: "Garrett Wilson", position: P.WR, team: "NYJ", byeWeek: 12, tier: 2, adp: 10, espnRank: 9, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 28, gamesPlayed2024: 17, stats2024: { receptions: 95, receivingYards: 1042, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 100, receivingYards: 1350, receivingTds: 8 }, espnPpgProjected: 16.5, sleeperPpgProjected: 17.2, archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Elite talent finally getting a great QB"], concerns: ["Very difficult schedule for WRs"] } },
    { id: 8, name: "Aaron Rodgers", position: P.QB, team: "NYJ", byeWeek: 12, tier: 7, adp: 100, espnRank: 105, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 28, gamesPlayed2024: 1, stats2024: { passingYards: 0, passingTds: 0, interceptions: 0 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 4200, passingTds: 32, interceptions: 8 }, espnPpgProjected: 17.5, sleeperPpgProjected: 18.0, archetype: "Veteran Pocket Passer" },
    { id: 9, name: "Mike Williams", position: P.WR, team: "NYJ", byeWeek: 12, tier: 8, adp: 120, espnRank: 125, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 28, gamesPlayed2024: 3, stats2024: { receptions: 19, receivingYards: 249, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { receptions: 55, receivingYards: 800, receivingTds: 6 }, espnPpgProjected: 10.5, sleeperPpgProjected: 11.0, archetype: "Contested Catch Specialist" },
    
    // Dallas Cowboys
    { id: 10, name: "CeeDee Lamb", position: P.WR, team: "DAL", byeWeek: 7, tier: 1, adp: 2, espnRank: 2, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 12, gamesPlayed2024: 17, stats2024: { receptions: 135, receivingYards: 1749, receivingTds: 12 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 125, receivingYards: 1600, receivingTds: 11 }, espnPpgProjected: 20.5, sleeperPpgProjected: 21.1, archetype: "PPR Machine", projectionModifiers: { catalysts: ["Focal point of a pass-heavy offense"], concerns: ["Potential contract holdout"] } },
    { id: 11, name: "Dak Prescott", position: P.QB, team: "DAL", byeWeek: 7, tier: 4, adp: 60, espnRank: 62, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 12, gamesPlayed2024: 17, stats2024: { passingYards: 4516, passingTds: 36, interceptions: 9, rushingYards: 242, rushingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4400, passingTds: 32, interceptions: 11, rushingYards: 200, rushingTds: 3 }, espnPpgProjected: 19.5, sleeperPpgProjected: 19.9, archetype: "Pocket Passer" },
    { id: 12, name: "Ezekiel Elliott", position: P.RB, team: "DAL", byeWeek: 7, tier: 7, adp: 105, espnRank: 110, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 9, gamesPlayed2024: 17, stats2024: { rushingYards: 642, rushingTds: 3, receptions: 51, receivingYards: 313, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 700, rushingTds: 6, receptions: 35, receivingYards: 200, receivingTds: 1 }, espnPpgProjected: 9.8, sleeperPpgProjected: 10.2, archetype: "Goal-line Grinder" },
    { id: 13, name: "Jake Ferguson", position: P.TE, team: "DAL", byeWeek: 7, tier: 6, adp: 80, espnRank: 78, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 11, gamesPlayed2024: 17, stats2024: { receptions: 71, receivingYards: 761, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 75, receivingYards: 800, receivingTds: 6 }, espnPpgProjected: 10.2, sleeperPpgProjected: 10.8, archetype: "Possession TE" },
    { id: 14, name: "Brandin Cooks", position: P.WR, team: "DAL", byeWeek: 7, tier: 8, adp: 130, espnRank: 135, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 12, gamesPlayed2024: 16, stats2024: { receptions: 54, receivingYards: 657, receivingTds: 8 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 55, receivingYards: 700, receivingTds: 6 }, espnPpgProjected: 9.5, sleeperPpgProjected: 9.9, archetype: "Veteran Deep Threat" },
    
    // Miami Dolphins
    { id: 15, name: "Tyreek Hill", position: P.WR, team: "MIA", byeWeek: 6, tier: 1, adp: 3, espnRank: 4, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 2, gamesPlayed2024: 16, stats2024: { receptions: 119, receivingYards: 1799, receivingTds: 13 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 110, receivingYards: 1650, receivingTds: 12 }, espnPpgProjected: 19.8, sleeperPpgProjected: 20.5, archetype: "Game-Breaking Speedster", projectionModifiers: { catalysts: ["Most explosive player in the league"], concerns: ["Age/potential decline", "Nagging injuries"] } },
    { id: 16, name: "Jaylen Waddle", position: P.WR, team: "MIA", byeWeek: 6, tier: 4, adp: 26, espnRank: 25, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 2, gamesPlayed2024: 14, stats2024: { receptions: 72, receivingYards: 1014, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 80, receivingYards: 1100, receivingTds: 6 }, espnPpgProjected: 13.8, sleeperPpgProjected: 14.5, archetype: "Explosive #2 WR" },
    { id: 17, name: "De'Von Achane", position: P.RB, team: "MIA", byeWeek: 6, tier: 3, adp: 20, espnRank: 22, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 5, gamesPlayed2024: 11, stats2024: { rushingYards: 800, rushingTds: 8, receptions: 27, receivingYards: 197, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { rushingYards: 900, rushingTds: 9, receptions: 35, receivingYards: 250, receivingTds: 3 }, espnPpgProjected: 15.5, sleeperPpgProjected: 16.0, archetype: "Home Run Hitter" },
    { id: 18, name: "Tua Tagovailoa", position: P.QB, team: "MIA", byeWeek: 6, tier: 6, adp: 95, espnRank: 98, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 2, gamesPlayed2024: 17, stats2024: { passingYards: 4624, passingTds: 29, interceptions: 14 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 4500, passingTds: 28, interceptions: 13 }, espnPpgProjected: 18.2, sleeperPpgProjected: 18.5, archetype: "System QB" },
    { id: 19, name: "Raheem Mostert", position: P.RB, team: "MIA", byeWeek: 6, tier: 6, adp: 98, espnRank: 102, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 5, gamesPlayed2024: 15, stats2024: { rushingYards: 1012, rushingTds: 18, receptions: 25, receivingYards: 175, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { rushingYards: 800, rushingTds: 10, receptions: 20, receivingYards: 150, receivingTds: 2 }, espnPpgProjected: 11.8, sleeperPpgProjected: 12.1, archetype: "Veteran Speedster" },

    // Minnesota Vikings
    { id: 20, name: "Justin Jefferson", position: P.WR, team: "MIN", byeWeek: 6, tier: 1, adp: 7, espnRank: 8, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 18, gamesPlayed2024: 10, stats2024: { receptions: 68, receivingYards: 1074, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 105, receivingYards: 1600, receivingTds: 9 }, espnPpgProjected: 18.5, sleeperPpgProjected: 19.2, notes: "Still arguably the best WR in the NFL, but has QB uncertainty.", archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Arguably the most talented WR in NFL"], concerns: ["Major QB downgrade", "Returning from injury"] } },
    { id: 21, name: "Aaron Jones", position: P.RB, team: "MIN", byeWeek: 6, tier: 4, adp: 45, espnRank: 48, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 13, gamesPlayed2024: 11, stats2024: { rushingYards: 656, rushingTds: 2, receptions: 30, receivingYards: 233, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { rushingYards: 900, rushingTds: 6, receptions: 40, receivingYards: 300, receivingTds: 2 }, espnPpgProjected: 12.8, sleeperPpgProjected: 13.5, archetype: "Dual-Threat Veteran" },
    { id: 22, name: "Jordan Addison", position: P.WR, team: "MIN", byeWeek: 6, tier: 6, adp: 65, espnRank: 68, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 18, gamesPlayed2024: 17, stats2024: { receptions: 70, receivingYards: 911, receivingTds: 10 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 75, receivingYards: 950, receivingTds: 8 }, espnPpgProjected: 12.5, sleeperPpgProjected: 13.0, archetype: "Complementary WR" },
    { id: 23, name: "T.J. Hockenson", position: P.TE, team: "MIN", byeWeek: 6, tier: 7, adp: 110, espnRank: 112, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 17, gamesPlayed2024: 15, stats2024: { receptions: 95, receivingYards: 960, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 12, stats2025Projected: { receptions: 70, receivingYards: 700, receivingTds: 4 }, espnPpgProjected: 10.0, sleeperPpgProjected: 10.5, notes: "Elite TE talent, but likely to miss start of season recovering from ACL/MCL surgery.", archetype: "Possession TE" },
    { id: 24, name: "J.J. McCarthy", position: P.QB, team: "MIN", byeWeek: 6, tier: 10, adp: 200, espnRank: 210, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 18, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { passingYards: 3500, passingTds: 20, interceptions: 12, rushingYards: 250, rushingTds: 3 }, espnPpgProjected: 15.0, sleeperPpgProjected: 15.8, archetype: "Rookie QB" },
    
    // Arizona Cardinals
    { id: 25, name: "Marvin Harrison Jr.", position: P.WR, team: "ARI", byeWeek: 11, tier: 2, adp: 16, espnRank: 16, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 1, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 95, receivingYards: 1350, receivingTds: 9 }, espnPpgProjected: 17.1, sleeperPpgProjected: 17.5, notes: "Best WR prospect in years, immediate alpha in his offense.", archetype: "Rookie Phenom WR", projectionModifiers: { catalysts: ["Generational prospect", "Immediate #1 WR role"], concerns: ["Rookie QB growing pains possible"] } },
    { id: 26, name: "Kyler Murray", position: P.QB, team: "ARI", byeWeek: 11, tier: 5, adp: 65, espnRank: 68, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 10, gamesPlayed2024: 8, stats2024: { passingYards: 1799, passingTds: 10, interceptions: 5, rushingYards: 244, rushingTds: 3 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 3900, passingTds: 24, interceptions: 10, rushingYards: 520, rushingTds: 6 }, espnPpgProjected: 19.8, sleeperPpgProjected: 20.5, archetype: "Konami Code QB", projectionModifiers: { catalysts: ["Elite new weapon in Marvin Harrison Jr.", "High rushing floor"], concerns: ["Offensive line questions", "Consistency issues"] } },
    { id: 27, name: "James Conner", position: P.RB, team: "ARI", byeWeek: 11, tier: 5, adp: 68, espnRank: 70, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 16, gamesPlayed2024: 13, stats2024: { rushingYards: 1040, rushingTds: 7, receptions: 27, receivingYards: 165, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 13, stats2025Projected: { rushingYards: 850, rushingTds: 7, receptions: 28, receivingYards: 180, receivingTds: 1 }, espnPpgProjected: 13.5, sleeperPpgProjected: 13.8, archetype: "Bell-cow RB", projectionModifiers: { catalysts: ["Clear lead back role", "Goal line usage"], concerns: ["High injury risk", "Explosive rookie competition"] } },
    { id: 28, name: "Trey McBride", position: P.TE, team: "ARI", byeWeek: 11, tier: 4, adp: 47, espnRank: 45, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 10, gamesPlayed2024: 17, stats2024: { receptions: 81, receivingYards: 825, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 90, receivingYards: 900, receivingTds: 5 }, espnPpgProjected: 12.2, sleeperPpgProjected: 12.8, notes: "Became a target monster, and should continue with Harrison Jr. drawing coverage.", archetype: "Possession TE" },
    { id: 29, name: "Trey Benson", position: P.RB, team: "ARI", byeWeek: 11, tier: 8, adp: 110, espnRank: 115, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 16, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 750, rushingTds: 6, receptions: 25, receivingYards: 200, receivingTds: 2 }, espnPpgProjected: 8.5, sleeperPpgProjected: 9.0, archetype: "Rookie Speedster", notes: "Explosive back who could take over the lead role." },
    
    // Atlanta Falcons
    { id: 30, name: "Bijan Robinson", position: P.RB, team: "ATL", byeWeek: 12, tier: 1, adp: 5, espnRank: 5, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 4, gamesPlayed2024: 17, stats2024: { rushingYards: 976, rushingTds: 4, receptions: 58, receivingYards: 487, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { rushingYards: 1300, rushingTds: 10, receptions: 70, receivingYards: 600, receivingTds: 5 }, espnPpgProjected: 19.5, sleeperPpgProjected: 20.2, archetype: "Elite All-Purpose Back" },
    { id: 31, name: "Drake London", position: P.WR, team: "ATL", byeWeek: 12, tier: 3, adp: 18, espnRank: 19, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 3, gamesPlayed2024: 16, stats2024: { receptions: 69, receivingYards: 905, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 85, receivingYards: 1200, receivingTds: 7 }, espnPpgProjected: 15.0, sleeperPpgProjected: 15.8, archetype: "Alpha X-Receiver" },
    { id: 32, name: "Kyle Pitts", position: P.TE, team: "ATL", byeWeek: 12, tier: 5, adp: 58, espnRank: 55, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 2, gamesPlayed2024: 17, stats2024: { receptions: 53, receivingYards: 667, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 70, receivingYards: 950, receivingTds: 6 }, espnPpgProjected: 11.0, sleeperPpgProjected: 11.7, archetype: "Move TE/Big Slot" },
    { id: 33, name: "Kirk Cousins", position: P.QB, team: "ATL", byeWeek: 12, tier: 7, adp: 115, espnRank: 118, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 3, gamesPlayed2024: 8, stats2024: { passingYards: 2331, passingTds: 18, interceptions: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 4500, passingTds: 30, interceptions: 10 }, espnPpgProjected: 19.0, sleeperPpgProjected: 19.5, archetype: "Veteran Pocket Passer" },
    
    // Houston Texans
    { id: 34, name: "C.J. Stroud", position: P.QB, team: "HOU", byeWeek: 14, tier: 2, adp: 30, espnRank: 32, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 23, gamesPlayed2024: 15, stats2024: { passingYards: 4108, passingTds: 23, interceptions: 5, rushingYards: 167, rushingTds: 3 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4700, passingTds: 35, interceptions: 8, rushingYards: 200, rushingTds: 3 }, espnPpgProjected: 22.5, sleeperPpgProjected: 23.0, archetype: "Elite Pocket Passer" },
    { id: 35, name: "Nico Collins", position: P.WR, team: "HOU", byeWeek: 14, tier: 3, adp: 22, espnRank: 21, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 23, gamesPlayed2024: 15, stats2024: { receptions: 80, receivingYards: 1297, receivingTds: 8 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 85, receivingYards: 1350, receivingTds: 9 }, espnPpgProjected: 16.2, sleeperPpgProjected: 16.8, archetype: "Alpha X-Receiver" },
    { id: 36, name: "Stefon Diggs", position: P.WR, team: "HOU", byeWeek: 14, tier: 5, adp: 40, espnRank: 42, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 23, gamesPlayed2024: 17, stats2024: { receptions: 107, receivingYards: 1183, receivingTds: 8 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 95, receivingYards: 1100, receivingTds: 7 }, espnPpgProjected: 14.5, sleeperPpgProjected: 15.0, archetype: "Veteran Route Runner" },
    { id: 37, name: "Joe Mixon", position: P.RB, team: "HOU", byeWeek: 14, tier: 4, adp: 38, espnRank: 40, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 21, gamesPlayed2024: 17, stats2024: { rushingYards: 1034, rushingTds: 9, receptions: 52, receivingYards: 376, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1000, rushingTds: 8, receptions: 50, receivingYards: 350, receivingTds: 2 }, espnPpgProjected: 14.0, sleeperPpgProjected: 14.6, archetype: "Bell-cow RB" },
    { id: 38, name: "Tank Dell", position: P.WR, team: "HOU", byeWeek: 14, tier: 6, adp: 50, espnRank: 52, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 23, gamesPlayed2024: 11, stats2024: { receptions: 47, receivingYards: 709, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 65, receivingYards: 950, receivingTds: 8 }, espnPpgProjected: 13.0, sleeperPpgProjected: 13.8, archetype: "Explosive Deep Threat" },
    { id: 39, name: "Dalton Schultz", position: P.TE, team: "HOU", byeWeek: 14, tier: 8, adp: 125, espnRank: 130, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2024: 15, stats2024: { receptions: 59, receivingYards: 635, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 60, receivingYards: 650, receivingTds: 5 }, espnPpgProjected: 9.0, sleeperPpgProjected: 9.4, archetype: "Possession TE" },

    // Philadelphia Eagles
    { id: 40, name: "A.J. Brown", position: P.WR, team: "PHI", byeWeek: 5, tier: 2, adp: 9, espnRank: 10, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 9, gamesPlayed2024: 17, stats2024: { receptions: 106, receivingYards: 1456, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 100, receivingYards: 1500, receivingTds: 9 }, espnPpgProjected: 17.8, sleeperPpgProjected: 18.2, archetype: "YAC Monster WR1" },
    { id: 41, name: "Saquon Barkley", position: P.RB, team: "PHI", byeWeek: 5, tier: 2, adp: 11, espnRank: 11, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 6, gamesPlayed2024: 14, stats2024: { rushingYards: 962, rushingTds: 6, receptions: 41, receivingYards: 280, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1100, rushingTds: 8, receptions: 50, receivingYards: 350, receivingTds: 3 }, espnPpgProjected: 17.5, sleeperPpgProjected: 18.0, archetype: "Dual-Threat RB1" },
    { id: 42, name: "Jalen Hurts", position: P.QB, team: "PHI", byeWeek: 5, tier: 1, adp: 15, espnRank: 15, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 9, gamesPlayed2024: 17, stats2024: { passingYards: 3858, passingTds: 23, interceptions: 15, rushingYards: 605, rushingTds: 15 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 3900, passingTds: 25, interceptions: 12, rushingYards: 650, rushingTds: 13 }, espnPpgProjected: 23.5, sleeperPpgProjected: 24.0, archetype: "Elite Konami Code QB" },
    { id: 43, name: "DeVonta Smith", position: P.WR, team: "PHI", byeWeek: 5, tier: 5, adp: 42, espnRank: 41, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 9, gamesPlayed2024: 16, stats2024: { receptions: 81, receivingYards: 1066, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 85, receivingYards: 1100, receivingTds: 7 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.0, archetype: "Elite Route Runner" },
    { id: 44, name: "Dallas Goedert", position: P.TE, team: "PHI", byeWeek: 5, tier: 7, adp: 90, espnRank: 92, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 8, gamesPlayed2024: 14, stats2024: { receptions: 59, receivingYards: 592, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 65, receivingYards: 700, receivingTds: 4 }, espnPpgProjected: 9.2, sleeperPpgProjected: 9.8, archetype: "All-Around TE" },
    
    // Chicago Bears
    { id: 45, name: "DJ Moore", position: P.WR, team: "CHI", byeWeek: 7, tier: 4, adp: 32, espnRank: 33, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 4, gamesPlayed2024: 17, stats2024: { receptions: 96, receivingYards: 1364, receivingTds: 8 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 90, receivingYards: 1200, receivingTds: 7 }, espnPpgProjected: 14.8, sleeperPpgProjected: 15.5, archetype: "Alpha X-Receiver" },
    { id: 46, name: "D'Andre Swift", position: P.RB, team: "CHI", byeWeek: 7, tier: 5, adp: 70, espnRank: 72, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 7, gamesPlayed2024: 16, stats2024: { rushingYards: 1049, rushingTds: 5, receptions: 39, receivingYards: 214, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 950, rushingTds: 6, receptions: 45, receivingYards: 300, receivingTds: 2 }, espnPpgProjected: 12.0, sleeperPpgProjected: 12.8, archetype: "Dual-Threat RB" },
    { id: 47, name: "Keenan Allen", position: P.WR, team: "CHI", byeWeek: 7, tier: 6, adp: 75, espnRank: 78, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 4, gamesPlayed2024: 13, stats2024: { receptions: 108, receivingYards: 1243, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 90, receivingYards: 1000, receivingTds: 6 }, espnPpgProjected: 13.2, sleeperPpgProjected: 13.9, archetype: "Veteran PPR Machine" },
    { id: 48, name: "Rome Odunze", position: P.WR, team: "CHI", byeWeek: 7, tier: 7, adp: 88, espnRank: 90, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 4, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 65, receivingYards: 850, receivingTds: 6 }, espnPpgProjected: 10.8, sleeperPpgProjected: 11.5, archetype: "Rookie Contested Catcher" },
    { id: 49, name: "Caleb Williams", position: P.QB, team: "CHI", byeWeek: 7, tier: 8, adp: 120, espnRank: 122, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 4, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4000, passingTds: 28, interceptions: 14, rushingYards: 350, rushingTds: 4 }, espnPpgProjected: 18.0, sleeperPpgProjected: 18.8, archetype: "Rookie Gunslinger" },
    { id: 50, name: "Cole Kmet", position: P.TE, team: "CHI", byeWeek: 7, tier: 8, adp: 135, espnRank: 140, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 6, gamesPlayed2024: 17, stats2024: { receptions: 73, receivingYards: 719, receivingTds: 6 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 70, receivingYards: 700, receivingTds: 5 }, espnPpgProjected: 9.0, sleeperPpgProjected: 9.5, archetype: "Possession TE" },
    
    // Cincinnati Bengals
    { id: 301, name: "Ja'Marr Chase", position: P.WR, team: "CIN", byeWeek: 12, tier: 1, adp: 5, espnRank: 7, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 26, gamesPlayed2024: 16, stats2024: { receptions: 100, receivingYards: 1216, receivingTds: 7 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 105, receivingYards: 1400, receivingTds: 10 }, espnPpgProjected: 18.2, sleeperPpgProjected: 19.0, archetype: "Alpha Target Hog" },
    { id: 52, name: "Joe Burrow", position: P.QB, team: "CIN", byeWeek: 12, tier: 3, adp: 48, espnRank: 50, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 26, gamesPlayed2024: 10, stats2024: { passingYards: 2309, passingTds: 15, interceptions: 6 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 4600, passingTds: 35, interceptions: 12 }, espnPpgProjected: 21.0, sleeperPpgProjected: 21.5, archetype: "Elite Pocket Passer" },
    { id: 53, name: "Tee Higgins", position: P.WR, team: "CIN", byeWeek: 12, tier: 6, adp: 55, espnRank: 58, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 26, gamesPlayed2024: 12, stats2024: { receptions: 42, receivingYards: 656, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 70, receivingYards: 1000, receivingTds: 6 }, espnPpgProjected: 12.5, sleeperPpgProjected: 13.0, archetype: "Contested Catch Specialist" },
    { id: 54, name: "Zack Moss", position: P.RB, team: "CIN", byeWeek: 12, tier: 6, adp: 82, espnRank: 85, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2024: 14, stats2024: { rushingYards: 794, rushingTds: 5, receptions: 27, receivingYards: 192, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 900, rushingTds: 7, receptions: 30, receivingYards: 200, receivingTds: 1 }, espnPpgProjected: 11.5, sleeperPpgProjected: 12.0, archetype: "Grinder" },
    
    // Detroit Lions
    { id: 298, name: "Amon-Ra St. Brown", position: P.WR, team: "DET", byeWeek: 5, tier: 1, adp: 6, espnRank: 6, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 16, gamesPlayed2024: 16, stats2024: { receptions: 119, receivingYards: 1515, receivingTds: 10 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 120, receivingYards: 1450, receivingTds: 9 }, espnPpgProjected: 18.8, sleeperPpgProjected: 19.5, archetype: "PPR Machine" },
    { id: 299, name: "Sam LaPorta", position: P.TE, team: "DET", byeWeek: 5, tier: 1, adp: 14, espnRank: 14, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 15, gamesPlayed2024: 17, stats2024: { receptions: 86, receivingYards: 889, receivingTds: 10 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 90, receivingYards: 950, receivingTds: 9 }, espnPpgProjected: 14.5, sleeperPpgProjected: 15.2, archetype: "Elite All-Around TE" },
    { id: 300, name: "Jahmyr Gibbs", position: P.RB, team: "DET", byeWeek: 5, tier: 2, adp: 12, espnRank: 12, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 10, gamesPlayed2024: 15, stats2024: { rushingYards: 945, rushingTds: 10, receptions: 52, receivingYards: 316, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1000, rushingTds: 9, receptions: 55, receivingYards: 350, receivingTds: 2 }, espnPpgProjected: 16.8, sleeperPpgProjected: 17.5, archetype: "Explosive Dual-Threat" },
    { id: 58, name: "Jared Goff", position: P.QB, team: "DET", byeWeek: 5, tier: 7, adp: 96, espnRank: 99, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 16, gamesPlayed2024: 17, stats2024: { passingYards: 4575, passingTds: 30, interceptions: 12 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4500, passingTds: 28, interceptions: 11 }, espnPpgProjected: 18.0, sleeperPpgProjected: 18.3, archetype: "System QB" },
    { id: 59, name: "Jameson Williams", position: P.WR, team: "DET", byeWeek: 5, tier: 8, adp: 118, espnRank: 120, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 16, gamesPlayed2024: 12, stats2024: { receptions: 24, receivingYards: 354, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 50, receivingYards: 800, receivingTds: 5 }, espnPpgProjected: 9.5, sleeperPpgProjected: 10.1, archetype: "Boom/Bust Deep Threat" },
    { id: 60, name: "David Montgomery", position: P.RB, team: "DET", byeWeek: 5, tier: 6, adp: 80, espnRank: 82, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 10, gamesPlayed2024: 14, stats2024: { rushingYards: 1015, rushingTds: 13 }, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { rushingYards: 900, rushingTds: 10 }, espnPpgProjected: 11.0, sleeperPpgProjected: 11.5, archetype: "Goal-line Grinder" },

    // Indianapolis Colts
    { id: 302, name: "Jonathan Taylor", position: P.RB, team: "IND", byeWeek: 14, tier: 2, adp: 13, espnRank: 13, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 1, gamesPlayed2024: 10, stats2024: { rushingYards: 741, rushingTds: 7, receptions: 19, receivingYards: 153, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1200, rushingTds: 10, receptions: 30, receivingYards: 200, receivingTds: 1 }, espnPpgProjected: 16.5, sleeperPpgProjected: 17.0, archetype: "Bell-cow RB" },
    { id: 62, name: "Anthony Richardson", position: P.QB, team: "IND", byeWeek: 14, tier: 3, adp: 35, espnRank: 38, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 7, gamesPlayed2024: 4, stats2024: { passingYards: 577, passingTds: 3, interceptions: 1, rushingYards: 136, rushingTds: 4 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { passingYards: 3500, passingTds: 20, interceptions: 10, rushingYards: 750, rushingTds: 8 }, espnPpgProjected: 21.5, sleeperPpgProjected: 22.0, archetype: "Elite Konami Code QB" },
    { id: 63, name: "Michael Pittman Jr.", position: P.WR, team: "IND", byeWeek: 14, tier: 5, adp: 45, espnRank: 48, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 7, gamesPlayed2024: 16, stats2024: { receptions: 109, receivingYards: 1152, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 100, receivingYards: 1100, receivingTds: 5 }, espnPpgProjected: 14.0, sleeperPpgProjected: 14.5, archetype: "Possession WR" },
    { id: 64, name: "Josh Downs", position: P.WR, team: "IND", byeWeek: 14, tier: 8, adp: 140, espnRank: 145, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 7, gamesPlayed2024: 17, stats2024: { receptions: 68, receivingYards: 771, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 70, receivingYards: 800, receivingTds: 4 }, espnPpgProjected: 9.8, sleeperPpgProjected: 10.2, archetype: "Slot Receiver" },

    // Los Angeles Rams
    { id: 303, name: "Kyren Williams", position: P.RB, team: "LAR", byeWeek: 6, tier: 2, adp: 17, espnRank: 18, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 8, gamesPlayed2024: 12, stats2024: { rushingYards: 1144, rushingTds: 12, receptions: 32, receivingYards: 206, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { rushingYards: 1000, rushingTds: 10, receptions: 35, receivingYards: 250, receivingTds: 2 }, espnPpgProjected: 17.0, sleeperPpgProjected: 17.6, archetype: "Workhorse RB" },
    { id: 66, name: "Puka Nacua", position: P.WR, team: "LAR", byeWeek: 6, tier: 3, adp: 24, espnRank: 23, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 5, gamesPlayed2024: 17, stats2024: { receptions: 105, receivingYards: 1486, receivingTds: 6 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 95, receivingYards: 1300, receivingTds: 7 }, espnPpgProjected: 16.0, sleeperPpgProjected: 16.8, archetype: "PPR Machine" },
    { id: 67, name: "Cooper Kupp", position: P.WR, team: "LAR", byeWeek: 6, tier: 6, adp: 62, espnRank: 65, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 5, gamesPlayed2024: 12, stats2024: { receptions: 59, receivingYards: 737, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 75, receivingYards: 900, receivingTds: 6 }, espnPpgProjected: 12.8, sleeperPpgProjected: 13.5, archetype: "Veteran Slot WR" },
    { id: 68, name: "Matthew Stafford", position: P.QB, team: "LAR", byeWeek: 6, tier: 8, adp: 130, espnRank: 132, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 5, gamesPlayed2024: 15, stats2024: { passingYards: 3965, passingTds: 24, interceptions: 11 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 4200, passingTds: 25, interceptions: 12 }, espnPpgProjected: 17.5, sleeperPpgProjected: 17.9, archetype: "Veteran Pocket Passer" },
    
    // New Orleans Saints
    { id: 304, name: "Chris Olave", position: P.WR, team: "NO", byeWeek: 12, tier: 3, adp: 19, espnRank: 20, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 17, gamesPlayed2024: 16, stats2024: { receptions: 87, receivingYards: 1123, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 90, receivingYards: 1250, receivingTds: 7 }, espnPpgProjected: 15.5, sleeperPpgProjected: 16.0, archetype: "Elite Route Runner" },
    { id: 70, name: "Alvin Kamara", position: P.RB, team: "NO", byeWeek: 12, tier: 5, adp: 60, espnRank: 64, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 11, gamesPlayed2024: 13, stats2024: { rushingYards: 694, rushingTds: 5, receptions: 75, receivingYards: 466, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { rushingYards: 700, rushingTds: 5, receptions: 65, receivingYards: 400, receivingTds: 2 }, espnPpgProjected: 13.8, sleeperPpgProjected: 14.2, archetype: "Receiving Back" },
    { id: 71, name: "Rashid Shaheed", position: P.WR, team: "NO", byeWeek: 12, tier: 9, adp: 160, espnRank: 165, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 17, gamesPlayed2024: 15, stats2024: { receptions: 46, receivingYards: 719, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 50, receivingYards: 800, receivingTds: 5 }, espnPpgProjected: 9.0, sleeperPpgProjected: 9.5, archetype: "Boom/Bust Deep Threat" },
    
    // Jacksonville Jaguars
    { id: 305, name: "Travis Etienne Jr.", position: P.RB, team: "JAX", byeWeek: 12, tier: 3, adp: 21, espnRank: 23, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 2, gamesPlayed2024: 17, stats2024: { rushingYards: 1008, rushingTds: 11, receptions: 58, receivingYards: 476, receivingTds: 1 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { rushingYards: 1050, rushingTds: 10, receptions: 60, receivingYards: 500, receivingTds: 2 }, espnPpgProjected: 16.0, sleeperPpgProjected: 16.5, archetype: "Dual-Threat RB" },
    { id: 73, name: "Christian Kirk", position: P.WR, team: "JAX", byeWeek: 12, tier: 6, adp: 72, espnRank: 75, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 8, gamesPlayed2024: 12, stats2024: { receptions: 57, receivingYards: 787, receivingTds: 3 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 75, receivingYards: 950, receivingTds: 5 }, espnPpgProjected: 12.0, sleeperPpgProjected: 12.8, archetype: "Slot Receiver" },
    { id: 74, name: "Evan Engram", position: P.TE, team: "JAX", byeWeek: 12, tier: 6, adp: 78, espnRank: 80, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 8, gamesPlayed2024: 17, stats2024: { receptions: 114, receivingYards: 963, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 100, receivingYards: 900, receivingTds: 5 }, espnPpgProjected: 12.0, sleeperPpgProjected: 12.5, archetype: "Move TE/Big Slot" },
    { id: 75, name: "Trevor Lawrence", position: P.QB, team: "JAX", byeWeek: 12, tier: 7, adp: 102, espnRank: 105, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 8, gamesPlayed2024: 16, stats2024: { passingYards: 4016, passingTds: 21, interceptions: 14, rushingYards: 339, rushingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4300, passingTds: 25, interceptions: 12, rushingYards: 350, rushingTds: 4 }, espnPpgProjected: 18.5, sleeperPpgProjected: 19.0, archetype: "Pocket Passer" },
    { id: 76, name: "Brian Thomas Jr.", position: P.WR, team: "JAX", byeWeek: 12, tier: 7, adp: 95, espnRank: 100, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 8, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 60, receivingYards: 900, receivingTds: 7 }, espnPpgProjected: 11.5, sleeperPpgProjected: 12.0, archetype: "Rookie Deep Threat" },
    
    // Washington Commanders
    { id: 306, name: "Jayden Daniels", position: P.QB, team: "WAS", byeWeek: 14, tier: 8, adp: 124, espnRank: 128, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 19, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 3600, passingTds: 22, interceptions: 12, rushingYards: 700, rushingTds: 6 }, espnPpgProjected: 19.2, sleeperPpgProjected: 20.0, archetype: "Rookie Konami Code QB" },
    { id: 78, name: "Terry McLaurin", position: P.WR, team: "WAS", byeWeek: 14, tier: 7, adp: 85, espnRank: 88, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 19, gamesPlayed2024: 17, stats2024: { receptions: 79, receivingYards: 1002, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 80, receivingYards: 1100, receivingTds: 6 }, espnPpgProjected: 12.8, sleeperPpgProjected: 13.2, archetype: "Alpha X-Receiver" },
    { id: 79, name: "Brian Robinson Jr.", position: P.RB, team: "WAS", byeWeek: 14, tier: 7, adp: 108, espnRank: 112, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 24, gamesPlayed2024: 15, stats2024: { rushingYards: 733, rushingTds: 5, receptions: 36, receivingYards: 368, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 800, rushingTds: 6, receptions: 30, receivingYards: 250, receivingTds: 2 }, espnPpgProjected: 10.5, sleeperPpgProjected: 11.0, archetype: "Grinder" },
    
    // New York Giants
    { id: 307, name: "Malik Nabers", position: P.WR, team: "NYG", byeWeek: 11, tier: 5, adp: 41, espnRank: 44, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 20, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 85, receivingYards: 1150, receivingTds: 7 }, espnPpgProjected: 14.2, sleeperPpgProjected: 15.0, archetype: "Rookie YAC Monster" },
    { id: 81, name: "Devin Singletary", position: P.RB, team: "NYG", byeWeek: 11, tier: 7, adp: 98, espnRank: 101, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 14, gamesPlayed2024: 17, stats2024: { rushingYards: 898, rushingTds: 4, receptions: 30, receivingYards: 191, receivingTds: 0 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 950, rushingTds: 5, receptions: 35, receivingYards: 200, receivingTds: 1 }, espnPpgProjected: 10.8, sleeperPpgProjected: 11.2, archetype: "Grinder" },

    // Kansas City Chiefs
    { id: 82, name: "Patrick Mahomes", position: P.QB, team: "KC", byeWeek: 6, tier: 1, adp: 25, espnRank: 28, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 21, gamesPlayed2024: 16, stats2024: { passingYards: 4183, passingTds: 27, interceptions: 14 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4700, passingTds: 35, interceptions: 12, rushingYards: 400, rushingTds: 3 }, espnPpgProjected: 22.0, sleeperPpgProjected: 22.8, archetype: "Elite Pocket Passer" },
    { id: 83, name: "Travis Kelce", position: P.TE, team: "KC", byeWeek: 6, tier: 2, adp: 29, espnRank: 30, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 20, gamesPlayed2024: 15, stats2024: { receptions: 93, receivingYards: 984, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 90, receivingYards: 1000, receivingTds: 7 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.0, archetype: "Elite Receiving TE" },
    { id: 84, name: "Isiah Pacheco", position: P.RB, team: "KC", byeWeek: 6, tier: 4, adp: 36, espnRank: 39, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 18, gamesPlayed2024: 14, stats2024: { rushingYards: 935, rushingTds: 7, receptions: 44, receivingYards: 244, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1000, rushingTds: 8, receptions: 40, receivingYards: 250, receivingTds: 2 }, espnPpgProjected: 14.2, sleeperPpgProjected: 14.8, archetype: "Violent Runner" },
    { id: 85, name: "Marquise Brown", position: P.WR, team: "KC", byeWeek: 6, tier: 7, adp: 84, espnRank: 86, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 21, gamesPlayed2024: 14, stats2024: { receptions: 51, receivingYards: 574, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { receptions: 70, receivingYards: 900, receivingTds: 6 }, espnPpgProjected: 11.8, sleeperPpgProjected: 12.5, archetype: "Deep Threat" },
    { id: 86, name: "Xavier Worthy", position: P.WR, team: "KC", byeWeek: 6, tier: 8, adp: 105, espnRank: 108, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 21, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 60, receivingYards: 850, receivingTds: 5 }, espnPpgProjected: 10.5, sleeperPpgProjected: 11.2, archetype: "Rookie Speedster" },

    // Baltimore Ravens
    { id: 87, name: "Lamar Jackson", position: P.QB, team: "BAL", byeWeek: 14, tier: 2, adp: 26, espnRank: 24, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2024: 16, stats2024: { passingYards: 3678, passingTds: 24, interceptions: 7, rushingYards: 821, rushingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 3700, passingTds: 25, interceptions: 8, rushingYards: 850, rushingTds: 6 }, espnPpgProjected: 22.8, sleeperPpgProjected: 23.5, archetype: "Elite Konami Code QB" },
    { id: 88, name: "Derrick Henry", position: P.RB, team: "BAL", byeWeek: 14, tier: 3, adp: 23, espnRank: 25, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2024: 17, stats2024: { rushingYards: 1167, rushingTds: 12, receptions: 28, receivingYards: 214, receivingTds: 0 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1200, rushingTds: 13, receptions: 20, receivingYards: 150, receivingTds: 0 }, espnPpgProjected: 15.8, sleeperPpgProjected: 16.2, archetype: "Workhorse RB" },
    { id: 89, name: "Mark Andrews", position: P.TE, team: "BAL", byeWeek: 14, tier: 3, adp: 34, espnRank: 35, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 24, gamesPlayed2024: 10, stats2024: { receptions: 45, receivingYards: 544, receivingTds: 6 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 70, receivingYards: 850, receivingTds: 7 }, espnPpgProjected: 13.0, sleeperPpgProjected: 13.6, archetype: "Elite Receiving TE" },
    { id: 90, name: "Zay Flowers", position: P.WR, team: "BAL", byeWeek: 14, tier: 6, adp: 68, espnRank: 70, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2024: 16, stats2024: { receptions: 77, receivingYards: 858, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 80, receivingYards: 900, receivingTds: 5 }, espnPpgProjected: 12.0, sleeperPpgProjected: 12.5, archetype: "YAC Specialist" },

    // Green Bay Packers
    { id: 91, name: "Jordan Love", position: P.QB, team: "GB", byeWeek: 10, tier: 5, adp: 63, espnRank: 66, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2024: 17, stats2024: { passingYards: 4159, passingTds: 32, interceptions: 11, rushingYards: 247, rushingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4200, passingTds: 30, interceptions: 12, rushingYards: 250, rushingTds: 3 }, espnPpgProjected: 19.8, sleeperPpgProjected: 20.2, archetype: "Pocket Passer" },
    { id: 92, name: "Josh Jacobs", position: P.RB, team: "GB", byeWeek: 10, tier: 4, adp: 40, espnRank: 43, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 17, gamesPlayed2024: 13, stats2024: { rushingYards: 805, rushingTds: 6, receptions: 37, receivingYards: 296, receivingTds: 0 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1100, rushingTds: 8, receptions: 45, receivingYards: 350, receivingTds: 1 }, espnPpgProjected: 14.5, sleeperPpgProjected: 15.0, archetype: "Bell-cow RB" },
    { id: 93, name: "Jayden Reed", position: P.WR, team: "GB", byeWeek: 10, tier: 6, adp: 74, espnRank: 76, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2024: 16, stats2024: { receptions: 64, receivingYards: 793, receivingTds: 8, rushingYards: 119, rushingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 70, receivingYards: 850, receivingTds: 7 }, espnPpgProjected: 12.2, sleeperPpgProjected: 12.8, archetype: "Versatile WR" },
    { id: 94, name: "Christian Watson", position: P.WR, team: "GB", byeWeek: 10, tier: 7, adp: 92, espnRank: 95, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 22, gamesPlayed2024: 9, stats2024: { receptions: 28, receivingYards: 422, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 14, stats2025Projected: { receptions: 50, receivingYards: 800, receivingTds: 6 }, espnPpgProjected: 11.5, sleeperPpgProjected: 12.0, archetype: "Boom/Bust Deep Threat" },

    // Buffalo Bills
    { id: 95, name: "Josh Allen", position: P.QB, team: "BUF", byeWeek: 12, tier: 1, adp: 13, espnRank: 12, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 30, gamesPlayed2024: 17, stats2024: { passingYards: 4306, passingTds: 29, interceptions: 18, rushingYards: 524, rushingTds: 15 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { passingYards: 4400, passingTds: 30, interceptions: 16, rushingYards: 550, rushingTds: 12 }, espnPpgProjected: 24.5, sleeperPpgProjected: 25.0, archetype: "Elite Konami Code QB" },
    { id: 96, name: "James Cook", position: P.RB, team: "BUF", byeWeek: 12, tier: 5, adp: 54, espnRank: 56, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 31, gamesPlayed2024: 17, stats2024: { rushingYards: 1122, rushingTds: 2, receptions: 44, receivingYards: 445, receivingTds: 4 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { rushingYards: 1000, rushingTds: 4, receptions: 50, receivingYards: 450, receivingTds: 3 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.0, archetype: "Receiving Back" },
    { id: 97, name: "Dalton Kincaid", position: P.TE, team: "BUF", byeWeek: 12, tier: 5, adp: 58, espnRank: 60, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 30, gamesPlayed2024: 16, stats2024: { receptions: 73, receivingYards: 673, receivingTds: 2 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 85, receivingYards: 800, receivingTds: 5 }, espnPpgProjected: 11.2, sleeperPpgProjected: 11.8, archetype: "Move TE/Big Slot" },
    { id: 98, name: "Keon Coleman", position: P.WR, team: "BUF", byeWeek: 12, tier: 8, adp: 112, espnRank: 115, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 30, gamesPlayed2024: 0, stats2024: {}, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 70, receivingYards: 900, receivingTds: 7 }, espnPpgProjected: 11.0, sleeperPpgProjected: 11.5, archetype: "Rookie X-Receiver" },

    // Additional Players
    { id: 100, name: "Lamar Jackson", position: P.QB, team: "BAL", byeWeek: 14, tier: 1, adp: 26, espnRank: 24, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2024: 16, stats2024: { passingYards: 3678, passingTds: 24, interceptions: 7, rushingYards: 821, rushingTds: 5 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { passingYards: 3700, passingTds: 25, interceptions: 8, rushingYards: 850, rushingTds: 6 }, espnPpgProjected: 22.8, sleeperPpgProjected: 23.5, archetype: "Elite Konami Code QB" },
    { id: 101, name: "Derrick Henry", position: P.RB, team: "BAL", byeWeek: 14, tier: 3, adp: 23, espnRank: 25, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2024: 17, stats2024: { rushingYards: 1167, rushingTds: 12, receptions: 28, receivingYards: 214, receivingTds: 0 }, drafted: false, gamesPlayed2025Projected: 16, stats2025Projected: { rushingYards: 1200, rushingTds: 13, receptions: 20, receivingYards: 150, receivingTds: 0 }, espnPpgProjected: 15.8, sleeperPpgProjected: 16.2, archetype: "Workhorse RB" },
    { id: 102, name: "Mark Andrews", position: P.TE, team: "BAL", byeWeek: 14, tier: 3, adp: 34, espnRank: 35, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 24, gamesPlayed2024: 10, stats2024: { receptions: 45, receivingYards: 544, receivingTds: 6 }, drafted: false, gamesPlayed2025Projected: 15, stats2025Projected: { receptions: 70, receivingYards: 850, receivingTds: 7 }, espnPpgProjected: 13.0, sleeperPpgProjected: 13.6, archetype: "Elite Receiving TE" },
    { id: 103, name: "Zay Flowers", position: P.WR, team: "BAL", byeWeek: 14, tier: 6, adp: 68, espnRank: 70, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2024: 16, stats2024: { receptions: 77, receivingYards: 858, receivingTds: 5 }, drafted: false, gamesPlayed2025Projected: 17, stats2025Projected: { receptions: 80, receivingYards: 900, receivingTds: 5 }, espnPpgProjected: 12.0, sleeperPpgProjected: 12.5, archetype: "YAC Specialist" },

    // Kickers & DSTs (Sample)
    { id: 289, name: "Kansas City Chiefs", position: P.DST, team: "KC", byeWeek: 6, tier: 10, adp: 150, espnRank: 145, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { sacks: 57, defensiveInterceptions: 8, fumblesRecovered: 11, pointsAllowed: 294, defensiveTds: 2 }, drafted: false, stats2025Projected: { sacks: 55, defensiveInterceptions: 10, fumblesRecovered: 10, pointsAllowed: 310, defensiveTds: 2 }, gamesPlayed2025Projected: 17, archetype: "DST" },
    { id: 290, name: "Baltimore Ravens", position: P.DST, team: "BAL", byeWeek: 14, tier: 10, adp: 152, espnRank: 148, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { sacks: 60, defensiveInterceptions: 18, fumblesRecovered: 12, pointsAllowed: 280, defensiveTds: 3 }, drafted: false, stats2025Projected: { sacks: 58, defensiveInterceptions: 16, fumblesRecovered: 11, pointsAllowed: 300, defensiveTds: 3 }, gamesPlayed2025Projected: 17, archetype: "DST" },
    { id: 291, name: "Cleveland Browns", position: P.DST, team: "CLE", byeWeek: 10, tier: 10, adp: 155, espnRank: 150, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { sacks: 49, defensiveInterceptions: 18, fumblesRecovered: 10, pointsAllowed: 362, defensiveTds: 4 }, drafted: false, stats2025Projected: { sacks: 50, defensiveInterceptions: 17, fumblesRecovered: 9, pointsAllowed: 350, defensiveTds: 3 }, gamesPlayed2025Projected: 17, archetype: "DST" },
    { id: 292, name: "Justin Tucker", position: P.K, team: "BAL", byeWeek: 14, tier: 11, adp: 160, espnRank: 155, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { fieldGoalsMade0to39: 15, fieldGoalsMade40to49: 12, fieldGoalsMade50plus: 5, extraPointsMade: 51 }, drafted: false, stats2025Projected: { fieldGoalsMade0to39: 14, fieldGoalsMade40to49: 11, fieldGoalsMade50plus: 6, extraPointsMade: 50 }, gamesPlayed2025Projected: 17, archetype: "Kicker" },
    { id: 293, name: "Jake Moody", position: P.K, team: "SF", byeWeek: 9, tier: 11, adp: 162, espnRank: 158, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { fieldGoalsMade0to39: 15, fieldGoalsMade40to49: 5, fieldGoalsMade50plus: 1, extraPointsMade: 60 }, drafted: false, stats2025Projected: { fieldGoalsMade0to39: 16, fieldGoalsMade40to49: 6, fieldGoalsMade50plus: 2, extraPointsMade: 58 }, gamesPlayed2025Projected: 17, archetype: "Kicker" },
    { id: 294, name: "Brandon Aubrey", position: P.K, team: "DAL", byeWeek: 7, tier: 11, adp: 165, espnRank: 160, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { fieldGoalsMade0to39: 16, fieldGoalsMade40to49: 10, fieldGoalsMade50plus: 10, extraPointsMade: 49 }, drafted: false, stats2025Projected: { fieldGoalsMade0to39: 15, fieldGoalsMade40to49: 9, fieldGoalsMade50plus: 9, extraPointsMade: 52 }, gamesPlayed2025Projected: 17, archetype: "Kicker" },
    { id: 295, name: "Indianapolis Colts", position: P.DST, team: "IND", byeWeek: 14, tier: 12, adp: 300, espnRank: 290, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { sacks: 51, defensiveInterceptions: 15, fumblesRecovered: 12, pointsAllowed: 415, defensiveTds: 5 }, drafted: false, stats2025Projected: { sacks: 48, defensiveInterceptions: 14, fumblesRecovered: 10, pointsAllowed: 400, defensiveTds: 4 }, gamesPlayed2025Projected: 17, archetype: "DST" },
    { id: 296, name: "Washington Commanders", position: P.DST, team: "WAS", byeWeek: 14, tier: 12, adp: 330, espnRank: 325, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 17, stats2024: { sacks: 39, defensiveInterceptions: 9, fumblesRecovered: 9, pointsAllowed: 518 }, drafted: false, stats2025Projected: { sacks: 42, defensiveInterceptions: 11, fumblesRecovered: 10, pointsAllowed: 480 }, gamesPlayed2025Projected: 17, archetype: "DST" },
    { id: 297, name: "Evan McPherson", position: P.K, team: "CIN", byeWeek: 12, tier: 11, adp: 170, espnRank: 168, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 0, gamesPlayed2024: 16, stats2024: { fieldGoalsMade0to39: 10, fieldGoalsMade40to49: 9, fieldGoalsMade50plus: 7, extraPointsMade: 40 }, drafted: false, stats2025Projected: { fieldGoalsMade0to39: 12, fieldGoalsMade40to49: 10, fieldGoalsMade50plus: 8, extraPointsMade: 45 }, gamesPlayed2025Projected: 17, archetype: "Kicker" },
];

export const UPDATED_PLAYER_DATA_SIMULATION: (Partial<Player> & { id: number })[] = [
    {
        id: 1, // Christian McCaffrey
        adp: 2, // ADP dropped slightly
        notes: "Slightly lowered ADP due to minor camp concerns, but still elite.",
    },
    {
        id: 6, // Breece Hall
        espnRank: 2, // Moved up in ESPN ranks
        stats2025Projected: { rushingYards: 1200, rushingTds: 9, receptions: 90, receivingYards: 750, receivingTds: 6 },
    },
    {
        id: 20, // Justin Jefferson
        sleeperPpgProjected: 19.8, // Increased projection
    },
    {
        id: 302, // Jonathan Taylor
        injuryRisk: 'Medium',
        notes: "Injury risk downgraded from High to Medium after positive camp reports."
    },
    {
        id: 25, // Marvin Harrison Jr.
        adp: 14, // ADP rising
        espnRank: 15,
        espnPpgProjected: 17.5,
    }
];
