
import type { Player, Stats, Position } from './types';
import { Position as P } from './types';

export const POSITIONS: Position[] = [P.QB, P.RB, P.WR, P.TE, P.K, P.DST];

export const calculateFantasyPoints = (stats: Stats, position: Position, gamesPlayed: number): number => {
    let points = 0;
    if (!stats) return 0;

    // Standard PPR scoring
    points += (stats.passingYards ?? 0) * 0.04;
    points += (stats.passingTds ?? 0) * 4;
    points += (stats.interceptions ?? 0) * -2;
    points += (stats.rushingYards ?? 0) * 0.1;
    points += (stats.rushingTds ?? 0) * 6;
    points += (stats.receptions ?? 0) * 1; // PPR
    points += (stats.receivingYards ?? 0) * 0.1;
    points += (stats.receivingTds ?? 0) * 6;
    points += (stats.fumblesLost ?? 0) * -2;

    // Kicker scoring
    points += (stats.fieldGoalsMade0to39 ?? 0) * 3;
    points += (stats.fieldGoalsMade40to49 ?? 0) * 4;
    points += (stats.fieldGoalsMade50plus ?? 0) * 5;
    points += (stats.extraPointsMade ?? 0) * 1;

    // DST scoring
    points += (stats.sacks ?? 0) * 1;
    points += (stats.defensiveInterceptions ?? 0) * 2;
    points += (stats.fumblesRecovered ?? 0) * 2;
    points += (stats.safeties ?? 0) * 2;
    points += (stats.defensiveTds ?? 0) * 6;
    points += (stats.blockedKicks ?? 0) * 2;
    
    // Points allowed logic for DST (example scale)
    const pointsAllowed = stats.pointsAllowed;
    if (pointsAllowed !== undefined && position === P.DST) {
        if (pointsAllowed === 0) points += 10;
        else if (pointsAllowed <= 6) points += 7;
        else if (pointsAllowed <= 13) points += 4;
        else if (pointsAllowed <= 20) points += 1;
        else if (pointsAllowed <= 27) points += 0;
        else if (pointsAllowed <= 34) points += -1;
        else points += -4;
    }

    return parseFloat(points.toFixed(2));
};

export const INITIAL_PLAYERS: Player[] = [
    // Tier 1
    { id: 1, name: "Christian McCaffrey", position: P.RB, team: "SF", byeWeek: 9, tier: 1, adp: 1, espnRank: 1, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 15, gamesPlayed2023: 16, stats2023: { rushingYards: 1459, rushingTds: 14, receptions: 67, receivingYards: 564, receivingTds: 7 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { rushingYards: 1200, rushingTds: 12, receptions: 70, receivingYards: 600, receivingTds: 5 }, espnPpgProjected: 21.5, sleeperPpgProjected: 22.4, notes: "The consensus #1 overall pick in a high-powered offense.", archetype: "Elite All-Purpose Back", projectionModifiers: { catalysts: ["Focal point of elite offense", "High-value touches (receptions + goal line)"], concerns: ["Slight injury risk from massive workload"] } },
    { id: 2, name: "CeeDee Lamb", position: P.WR, team: "DAL", byeWeek: 7, tier: 1, adp: 2, espnRank: 2, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 21, gamesPlayed2023: 17, stats2023: { receptions: 135, receivingYards: 1749, receivingTds: 12, rushingYards: 113, rushingTds: 2 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 110, receivingYards: 1400, receivingTds: 9, rushingYards: 80, rushingTds: 1 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.1, notes: "Massive target share and coming off a career year.", archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Elite target share", "Contract year motivation"], concerns: ["Potential offensive scheme changes"] } },
    { id: 3, name: "Tyreek Hill", position: P.WR, team: "MIA", byeWeek: 11, tier: 1, adp: 3, espnRank: 4, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 7, gamesPlayed2023: 16, stats2023: { receptions: 119, receivingYards: 1799, receivingTds: 13 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { receptions: 110, receivingYards: 1650, receivingTds: 11 }, espnPpgProjected: 19.9, sleeperPpgProjected: 20.2, notes: "League-winning upside every week, but entering age-30 season.", archetype: "Field-Stretching Speedster", projectionModifiers: { catalysts: ["Explosive, innovative offense", "Favorable early schedule"], concerns: ["Entering age-30 season", "Retirement talk creates uncertainty"] } },
    { id: 6, name: "Breece Hall", position: P.RB, team: "NYJ", byeWeek: 12, tier: 1, adp: 4, espnRank: 3, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 20, gamesPlayed2023: 17, stats2023: { rushingYards: 994, rushingTds: 5, receptions: 76, receivingYards: 591, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { rushingYards: 1100, rushingTds: 7, receptions: 80, receivingYards: 650, receivingTds: 4 }, espnPpgProjected: 18.8, sleeperPpgProjected: 19.5, notes: "Explosive dual-threat back, set to benefit from Aaron Rodgers' return.", archetype: "Dual-Threat RB1", projectionModifiers: { catalysts: ["Massive QB upgrade", "Elite receiving role for an RB"], concerns: ["Tough division defenses"] } },
    { id: 24, name: "Ja'Marr Chase", position: P.WR, team: "CIN", byeWeek: 12, tier: 1, adp: 5, espnRank: 5, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 4, gamesPlayed2023: 16, stats2023: { receptions: 100, receivingYards: 1216, receivingTds: 7 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 105, receivingYards: 1300, receivingTds: 9 }, espnPpgProjected: 18.5, sleeperPpgProjected: 18.9, notes: "Elite WR1 with a healthy Joe Burrow back under center.", archetype: "Elite X-Receiver", projectionModifiers: { catalysts: ["Healthy elite QB returning", "Positive TD regression expected"], concerns: ["Shares targets with another great WR"] } },
    { id: 4, name: "Amon-Ra St. Brown", position: P.WR, team: "DET", byeWeek: 5, tier: 1, adp: 6, espnRank: 6, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 15, gamesPlayed2023: 16, stats2023: { receptions: 119, receivingYards: 1515, receivingTds: 10 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 115, receivingYards: 1400, receivingTds: 9 }, espnPpgProjected: 18.2, sleeperPpgProjected: 19.1, notes: "High-floor PPR machine in one of the league's best offenses.", archetype: "PPR Machine", projectionModifiers: { catalysts: ["Top option in elite offense", "Extremely high floor"], concerns: ["Other weapons could vulture TDs"] } },
    { id: 17, name: "Justin Jefferson", position: P.WR, team: "MIN", byeWeek: 6, tier: 1, adp: 7, espnRank: 8, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 18, gamesPlayed2023: 10, stats2023: { receptions: 68, receivingYards: 1074, receivingTds: 5 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { receptions: 100, receivingYards: 1500, receivingTds: 8 }, espnPpgProjected: 17.8, sleeperPpgProjected: 18.5, notes: "Still arguably the best WR in the NFL, but has QB uncertainty for the first time.", archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Arguably the most talented WR in NFL"], concerns: ["Major QB downgrade", "Returning from injury"] } },
    { id: 7, name: "Bijan Robinson", position: P.RB, team: "ATL", byeWeek: 12, tier: 1, adp: 8, espnRank: 7, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 9, gamesPlayed2023: 17, stats2023: { rushingYards: 976, rushingTds: 4, receptions: 58, receivingYards: 487, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { rushingYards: 1250, rushingTds: 9, receptions: 65, receivingYards: 550, receivingTds: 4 }, espnPpgProjected: 17.9, sleeperPpgProjected: 18.3, notes: "Set for a massive workload in a new, improved offense with Kirk Cousins.", archetype: "Dual-Threat RB1", projectionModifiers: { catalysts: ["New coaching staff should use him correctly", "Major QB upgrade"], concerns: ["Still shares backfield with Allgeier"] } },
    { id: 9, name: "A.J. Brown", position: P.WR, team: "PHI", byeWeek: 5, tier: 1, adp: 9, espnRank: 11, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 5, gamesPlayed2023: 17, stats2023: { receptions: 106, receivingYards: 1456, receivingTds: 7 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 100, receivingYards: 1400, receivingTds: 8 }, espnPpgProjected: 17.1, sleeperPpgProjected: 17.5, archetype: "Elite X-Receiver", projectionModifiers: { catalysts: ["Elite big-play ability"], concerns: ["Shares targets with DeVonta Smith", "Offense struggled late last season"] } },
    { id: 23, name: "Jonathan Taylor", position: P.RB, team: "IND", byeWeek: 14, tier: 1, adp: 10, espnRank: 9, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 6, gamesPlayed2023: 10, stats2023: { rushingYards: 741, rushingTds: 7, receptions: 19, receivingYards: 153, receivingTds: 1 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { rushingYards: 1150, rushingTds: 10, receptions: 25, receivingYards: 200, receivingTds: 1 }, espnPpgProjected: 16.5, sleeperPpgProjected: 17.0, notes: "Huge upside with Anthony Richardson's rushing threat opening lanes.", archetype: "Bell-cow RB", projectionModifiers: { catalysts: ["Rushing QB opens lanes", "Bell-cow role when healthy"], concerns: ["High injury risk", "Limited receiving work"] } },
    { id: 8, name: "Kyren Williams", position: P.RB, team: "LAR", byeWeek: 6, tier: 1, adp: 11, espnRank: 10, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 11, gamesPlayed2023: 12, stats2023: { rushingYards: 1144, rushingTds: 12, receptions: 32, receivingYards: 206, receivingTds: 3 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { rushingYards: 1100, rushingTds: 10, receptions: 35, receivingYards: 250, receivingTds: 2 }, espnPpgProjected: 16.2, sleeperPpgProjected: 16.8, notes: "True bell-cow role, but now has rookie Blake Corum competing for touches.", archetype: "Bell-cow RB", projectionModifiers: { catalysts: ["True bell-cow workload"], concerns: ["New competition from rookie Blake Corum", "Negative TD regression likely"] } },
    { id: 20, name: "Saquon Barkley", position: P.RB, team: "PHI", byeWeek: 5, tier: 1, adp: 12, espnRank: 12, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 2, gamesPlayed2023: 14, stats2023: { rushingYards: 962, rushingTds: 6, receptions: 41, receivingYards: 280, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { rushingYards: 1100, rushingTds: 8, receptions: 45, receivingYards: 300, receivingTds: 3 }, espnPpgProjected: 16.0, sleeperPpgProjected: 16.5, notes: "Major offensive upgrade, running behind the best O-Line of his career.", archetype: "Dual-Threat RB1", projectionModifiers: { catalysts: ["Best O-Line of his career", "Major offensive upgrade"], concerns: ["High injury risk", "QB vultures goal-line TDs"] } },
    
    // Tier 2
    { id: 10, name: "Garrett Wilson", position: P.WR, team: "NYJ", byeWeek: 12, tier: 2, adp: 13, espnRank: 13, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 19, gamesPlayed2023: 17, stats2023: { receptions: 95, receivingYards: 1042, receivingTds: 3 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 105, receivingYards: 1250, receivingTds: 7 }, espnPpgProjected: 16.4, sleeperPpgProjected: 17.0, notes: "Elite target earner who finally gets a massive QB upgrade.", archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Massive QB upgrade (A. Rodgers)", "Elite target earning ability"], concerns: ["Tough division defenses"] } },
    { id: 13, name: "Jahmyr Gibbs", position: P.RB, team: "DET", byeWeek: 5, tier: 2, adp: 14, espnRank: 14, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 13, gamesPlayed2023: 15, stats2023: { rushingYards: 945, rushingTds: 10, receptions: 52, receivingYards: 316, receivingTds: 1 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { rushingYards: 1000, rushingTds: 9, receptions: 55, receivingYards: 350, receivingTds: 2 }, espnPpgProjected: 15.5, sleeperPpgProjected: 16.0, notes: "Explosive home-run threat, but shares workload with Montgomery.", archetype: "Satellite Back Plus", projectionModifiers: { catalysts: ["Explosive plays in an elite offense"], concerns: ["Shares workload, especially at goal line", "Slight negative TD regression likely"] } },
    { id: 5, name: "Josh Allen", position: P.QB, team: "BUF", byeWeek: 12, tier: 2, adp: 15, espnRank: 15, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 22, gamesPlayed2023: 17, stats2023: { passingYards: 4306, passingTds: 29, interceptions: 18, rushingYards: 524, rushingTds: 15 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { passingYards: 4200, passingTds: 30, interceptions: 15, rushingYards: 550, rushingTds: 10 }, espnPpgProjected: 22.1, sleeperPpgProjected: 22.8, notes: "Lost his top WRs, but the 'Konami code' rushing upside keeps his floor incredibly high.", archetype: "Konami Code QB", projectionModifiers: { catalysts: ["Elite rushing TD upside"], concerns: ["Major downgrade in receiving weapons", "High interception rate"] } },
    { id: 25, name: "Marvin Harrison Jr.", position: P.WR, team: "ARI", byeWeek: 11, tier: 2, adp: 16, espnRank: 16, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 11, gamesPlayed2023: 0, stats2023: {}, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 90, receivingYards: 1200, receivingTds: 8 }, espnPpgProjected: 16.1, sleeperPpgProjected: 16.5, notes: "Best WR prospect in years, immediate alpha in his offense.", archetype: "Rookie Phenom WR", projectionModifiers: { catalysts: ["Generational prospect", "Immediate #1 WR role"], concerns: ["Rookie learning curve"] } },
    { id: 14, name: "Chris Olave", position: P.WR, team: "NO", byeWeek: 12, tier: 2, adp: 17, espnRank: 17, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 2, gamesPlayed2023: 16, stats2023: { receptions: 87, receivingYards: 1123, receivingTds: 5 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 90, receivingYards: 1250, receivingTds: 7 }, espnPpgProjected: 15.8, sleeperPpgProjected: 16.2, notes: "Elite route runner with a very favorable schedule to start the season.", archetype: "Elite Route Runner", projectionModifiers: { catalysts: ["Very favorable schedule", "Elite route-running ability"], concerns: ["Inconsistent QB play"] } },
    { id: 16, name: "Travis Etienne Jr.", position: P.RB, team: "JAX", byeWeek: 12, tier: 2, adp: 18, espnRank: 19, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 18, gamesPlayed2023: 17, stats2023: { rushingYards: 1008, rushingTds: 11, receptions: 58, receivingYards: 476, receivingTds: 1 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { rushingYards: 1000, rushingTds: 9, receptions: 50, receivingYards: 400, receivingTds: 2 }, espnPpgProjected: 15.0, sleeperPpgProjected: 15.5, archetype: "Workhorse RB", projectionModifiers: { catalysts: ["Workhorse volume", "Heavy involvement in passing game"], concerns: ["Inefficient offense", "Tank Bigsby could take goal line work"] } },
    { id: 28, name: "Puka Nacua", position: P.WR, team: "LAR", byeWeek: 6, tier: 2, adp: 19, espnRank: 20, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 20, gamesPlayed2023: 17, stats2023: { receptions: 105, receivingYards: 1486, receivingTds: 6 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 95, receivingYards: 1300, receivingTds: 7 }, espnPpgProjected: 15.9, sleeperPpgProjected: 16.4, notes: "Coming off a historic rookie season, but could see some target regression.", archetype: "PPR Machine", projectionModifiers: { catalysts: ["Excellent chemistry with Stafford"], concerns: ["Negative regression from historic rookie year is likely"] } },
    { id: 11, name: "Jalen Hurts", position: P.QB, team: "PHI", byeWeek: 5, tier: 2, adp: 20, espnRank: 21, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 11, gamesPlayed2023: 17, stats2023: { passingYards: 3858, passingTds: 23, interceptions: 15, rushingYards: 605, rushingTds: 15 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { passingYards: 3900, passingTds: 25, interceptions: 12, rushingYards: 600, rushingTds: 12 }, espnPpgProjected: 21.8, sleeperPpgProjected: 22.5, notes: "Rushing TD upside gives him a top-3 QB ceiling.", archetype: "Konami Code QB", projectionModifiers: { catalysts: ["Elite rushing TD upside", "Upgraded receiving weapons"], concerns: ["New offensive coordinator"] } },
    { id: 63, name: "De'Von Achane", position: P.RB, team: "MIA", byeWeek: 11, tier: 2, adp: 21, espnRank: 18, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 8, gamesPlayed2023: 11, stats2023: { rushingYards: 800, rushingTds: 8, receptions: 27, receivingYards: 197, receivingTds: 3 }, drafted: false, gamesPlayed2024Projected: 14, stats2024Projected: { rushingYards: 900, rushingTds: 9, receptions: 30, receivingYards: 250, receivingTds: 3 }, espnPpgProjected: 15.8, sleeperPpgProjected: 16.3, notes: "Most efficient RB in the league last year, but unlikely to see a massive workload.", archetype: "Boom/Bust Speedster", projectionModifiers: { catalysts: ["Historic efficiency", "Explosive offense"], concerns: ["Unlikely to see a large workload", "Shares backfield with Mostert"] } },
    { id: 12, name: "Sam LaPorta", position: P.TE, team: "DET", byeWeek: 5, tier: 2, adp: 22, espnRank: 22, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 14, gamesPlayed2023: 17, stats2023: { receptions: 86, receivingYards: 889, receivingTds: 10 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 85, receivingYards: 900, receivingTds: 8 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.0, archetype: "Elite Receiving TE", projectionModifiers: { catalysts: ["Top 2 target in an elite offense"], concerns: ["Negative TD regression is likely"] } },
    { id: 26, name: "Nico Collins", position: P.WR, team: "HOU", byeWeek: 14, tier: 2, adp: 23, espnRank: 24, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 25, gamesPlayed2023: 15, stats2023: { receptions: 80, receivingYards: 1297, receivingTds: 8 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { receptions: 80, receivingYards: 1250, receivingTds: 8 }, espnPpgProjected: 15.4, sleeperPpgProjected: 15.9, notes: "Breakout star, but now has Stefon Diggs competing for targets.", archetype: "Breakout WR1", projectionModifiers: { catalysts: ["Elite QB play from C.J. Stroud"], concerns: ["Major target competition added (S. Diggs)"] } },
    { id: 21, name: "Derrick Henry", position: P.RB, team: "BAL", byeWeek: 14, tier: 2, adp: 24, espnRank: 27, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 32, gamesPlayed2023: 17, stats2023: { rushingYards: 1167, rushingTds: 12, receptions: 28, receivingYards: 214, receivingTds: 0 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { rushingYards: 1200, rushingTds: 13, receptions: 20, receivingYards: 150, receivingTds: 0 }, espnPpgProjected: 14.5, sleeperPpgProjected: 15.0, notes: "Aging, but now on an elite offense with a history of productive run games.", archetype: "Power Back", projectionModifiers: { catalysts: ["Massive offense upgrade", "Huge TD potential"], concerns: ["Aging with high mileage", "Toughest schedule for RBs"] } },
    
    // Tier 3
    { id: 117, name: "Malik Nabers", position: P.WR, team: "NYG", byeWeek: 11, tier: 3, adp: 25, espnRank: 30, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 9, gamesPlayed2023: 0, stats2023: {}, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { receptions: 80, receivingYards: 1050, receivingTds: 6 }, espnPpgProjected: 13.8, sleeperPpgProjected: 14.2, notes: "Explosive rookie WR who projects as his team's #1 option immediately.", archetype: "Rookie Phenom WR", projectionModifiers: { catalysts: ["Immediate #1 WR role"], concerns: ["Poor QB play", "Rookie learning curve"] } },
    { id: 27, name: "Drake London", position: P.WR, team: "ATL", byeWeek: 12, tier: 3, adp: 26, espnRank: 23, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 1, gamesPlayed2023: 16, stats2023: { receptions: 68, receivingYards: 905, receivingTds: 2 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 85, receivingYards: 1150, receivingTds: 7 }, espnPpgProjected: 14.9, sleeperPpgProjected: 15.3, notes: "Major QB upgrade with Kirk Cousins could unlock his true potential.", archetype: "Breakout WR1", projectionModifiers: { catalysts: ["Major QB upgrade", "Easiest schedule for WRs"], concerns: ["Crowded receiving corps"] } },
    { id: 29, name: "DJ Moore", position: P.WR, team: "CHI", byeWeek: 7, tier: 3, adp: 27, espnRank: 28, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 26, gamesPlayed2023: 17, stats2023: { receptions: 96, receivingYards: 1364, receivingTds: 8 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 90, receivingYards: 1200, receivingTds: 7 }, espnPpgProjected: 15.2, sleeperPpgProjected: 15.6, notes: "Faces significantly more target competition with Keenan Allen and Rome Odunze.", archetype: "Alpha Target Hog", projectionModifiers: { catalysts: ["Potential QB upgrade with rookie"], concerns: ["Massive increase in target competition"] } },
    { id: 15, name: "Patrick Mahomes", position: P.QB, team: "KC", byeWeek: 6, tier: 3, adp: 28, espnRank: 26, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 15, gamesPlayed2023: 16, stats2023: { passingYards: 4183, passingTds: 27, interceptions: 14, rushingYards: 389, rushingTds: 0 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { passingYards: 4500, passingTds: 32, interceptions: 12, rushingYards: 350, rushingTds: 2 }, espnPpgProjected: 21.5, sleeperPpgProjected: 22.1, notes: "Best QB in the NFL with upgraded offensive weapons this season.", archetype: "Elite Pocket Passer", projectionModifiers: { catalysts: ["Best QB in NFL", "Upgraded receiving weapons"], concerns: [] } },
    { id: 22, name: "Isiah Pacheco", position: P.RB, team: "KC", byeWeek: 6, tier: 3, adp: 29, espnRank: 31, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 23, gamesPlayed2023: 14, stats2023: { rushingYards: 935, rushingTds: 7, receptions: 44, receivingYards: 244, receivingTds: 2 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { rushingYards: 1000, rushingTds: 8, receptions: 35, receivingYards: 200, receivingTds: 2 }, espnPpgProjected: 13.8, sleeperPpgProjected: 14.3, archetype: "Violent Rusher", projectionModifiers: { catalysts: ["Lead back on an elite offense"], concerns: ["Limited high-value touches (receptions)"] } },
    { id: 18, name: "Lamar Jackson", position: P.QB, team: "BAL", byeWeek: 14, tier: 3, adp: 30, espnRank: 33, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 29, gamesPlayed2023: 16, stats2023: { passingYards: 3678, passingTds: 24, interceptions: 7, rushingYards: 821, rushingTds: 5 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { passingYards: 3700, passingTds: 25, interceptions: 9, rushingYards: 800, rushingTds: 6 }, espnPpgProjected: 21.2, sleeperPpgProjected: 21.9, archetype: "Konami Code QB", projectionModifiers: { catalysts: ["Elite rushing floor"], concerns: ["Toughest schedule for QBs", "Loss of key offensive linemen"] } },
    { id: 30, name: "Jaylen Waddle", position: P.WR, team: "MIA", byeWeek: 11, tier: 3, adp: 31, espnRank: 25, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 7, gamesPlayed2023: 14, stats2023: { receptions: 72, receivingYards: 1014, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { receptions: 80, receivingYards: 1100, receivingTds: 5 }, espnPpgProjected: 14.2, sleeperPpgProjected: 14.6, archetype: "Field-Stretching Speedster", projectionModifiers: { catalysts: ["Explosive offense"], concerns: ["Clear #2 behind Tyreek Hill", "History of nagging injuries"] } },
    { id: 67, name: "Davante Adams", position: P.WR, team: "LV", byeWeek: 10, tier: 3, adp: 32, espnRank: 35, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 12, gamesPlayed2023: 17, stats2023: { receptions: 103, receivingYards: 1144, receivingTds: 8 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 100, receivingYards: 1100, receivingTds: 7 }, espnPpgProjected: 14.8, sleeperPpgProjected: 15.3, notes: "Still an elite talent, but facing poor QB play again this season.", archetype: "Veteran Target Hog", projectionModifiers: { catalysts: ["Massive target share"], concerns: ["Poor QB play", "Potential offensive decline"] } },
    { id: 19, name: "Travis Kelce", position: P.TE, team: "KC", byeWeek: 6, tier: 3, adp: 33, espnRank: 34, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 21, gamesPlayed2023: 15, stats2023: { receptions: 93, receivingYards: 984, receivingTds: 5 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { receptions: 90, receivingYards: 950, receivingTds: 6 }, espnPpgProjected: 13.0, sleeperPpgProjected: 13.5, notes: "Age and mileage are becoming a concern for the long-time TE1.", archetype: "Elite Receiving TE", projectionModifiers: { catalysts: ["Top target for best QB in NFL"], concerns: ["Age and mileage concerns", "Increased target competition"] } },
    { id: 68, name: "Michael Pittman Jr.", position: P.WR, team: "IND", byeWeek: 14, tier: 3, adp: 34, espnRank: 32, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 14, gamesPlayed2023: 16, stats2023: { receptions: 109, receivingYards: 1152, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 100, receivingYards: 1100, receivingTds: 5 }, espnPpgProjected: 14.5, sleeperPpgProjected: 15.0, archetype: "Possession WR1", projectionModifiers: { catalysts: ["High volume target", "Potential for more deep shots with Richardson"], concerns: ["Low TD upside"] } },
    { id: 64, name: "James Cook", position: P.RB, team: "BUF", byeWeek: 12, tier: 3, adp: 35, espnRank: 39, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 26, gamesPlayed2023: 17, stats2023: { rushingYards: 1122, rushingTds: 2, receptions: 44, receivingYards: 445, receivingTds: 4 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { rushingYards: 1000, rushingTds: 4, receptions: 50, receivingYards: 450, receivingTds: 3 }, espnPpgProjected: 12.8, sleeperPpgProjected: 13.2, notes: "Should see heavy involvement in the passing game, but lacks goal-line TDs.", archetype: "Satellite Back Plus", projectionModifiers: { catalysts: ["High receiving upside"], concerns: ["Lacks goal-line role", "QB vultures rushing TDs"] } },
    
    // Tier 4
    { id: 115, name: "DeVonta Smith", position: P.WR, team: "PHI", byeWeek: 5, tier: 4, adp: 36, espnRank: 38, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 5, gamesPlayed2023: 16, stats2023: { receptions: 81, receivingYards: 1066, receivingTds: 7 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 85, receivingYards: 1100, receivingTds: 7 }, espnPpgProjected: 13.9, sleeperPpgProjected: 14.4, archetype: "Elite Route Runner", projectionModifiers: { catalysts: ["Elite route runner on good offense"], concerns: ["Clear #2 target behind A.J. Brown"] } },
    { id: 118, name: "Rome Odunze", position: P.WR, team: "CHI", byeWeek: 7, tier: 4, adp: 37, espnRank: 41, opportunityShare: 'Medium', injuryRisk: 'Low', strengthOfSchedule: 26, gamesPlayed2023: 0, stats2023: {}, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 65, receivingYards: 900, receivingTds: 6 }, espnPpgProjected: 11.5, sleeperPpgProjected: 12.0, notes: "Extremely talented rookie, but is the #3 receiving option in his offense.", archetype: "Rookie Phenom WR", projectionModifiers: { catalysts: ["Extremely talented prospect"], concerns: ["#3 option in his own offense", "Rookie learning curve"] } },
    { id: 108, name: "Josh Jacobs", position: P.RB, team: "GB", byeWeek: 10, tier: 4, adp: 38, espnRank: 40, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 1, gamesPlayed2023: 13, stats2023: { rushingYards: 805, rushingTds: 6, receptions: 37, receivingYards: 296, receivingTds: 0 }, drafted: false, gamesPlayed2024Projected: 16, stats2024Projected: { rushingYards: 1000, rushingTds: 8, receptions: 40, receivingYards: 300, receivingTds: 1 }, espnPpgProjected: 13.5, sleeperPpgProjected: 14.0, archetype: "Workhorse RB", projectionModifiers: { catalysts: ["Upgraded offense", "Easiest schedule for RBs"], concerns: ["Injury history", "New team integration"] } },
    { id: 31, name: "C.J. Stroud", position: P.QB, team: "HOU", byeWeek: 14, tier: 4, adp: 40, espnRank: 38, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 18, gamesPlayed2023: 15, stats2023: { passingYards: 4108, passingTds: 23, interceptions: 5, rushingYards: 167, rushingTds: 3 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { passingYards: 4400, passingTds: 28, interceptions: 8, rushingYards: 150, rushingTds: 2 }, espnPpgProjected: 19.8, sleeperPpgProjected: 20.4, archetype: "Elite Pocket Passer", projectionModifiers: { catalysts: ["Elite accuracy and decision making", "Upgraded weapons (Diggs)"], concerns: ["Lacks rushing upside of other elite QBs"] } },
    { id: 139, name: "Deebo Samuel", position: P.WR, team: "SF", byeWeek: 9, tier: 4, adp: 41, espnRank: 43, opportunityShare: 'Medium', injuryRisk: 'Medium', strengthOfSchedule: 29, gamesPlayed2023: 15, stats2023: { receptions: 60, receivingYards: 892, receivingTds: 7, rushingYards: 225, rushingTds: 5 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { receptions: 60, receivingYards: 850, receivingTds: 6, rushingYards: 200, rushingTds: 4 }, espnPpgProjected: 14.0, sleeperPpgProjected: 14.5, archetype: "YAC Specialist", projectionModifiers: { catalysts: ["Unique 'wide back' role", "Explosive after the catch"], concerns: ["Nagging injury history", "Crowded with other elite weapons"] } },
    { id: 116, name: "Cooper Kupp", position: P.WR, team: "LAR", byeWeek: 6, tier: 4, adp: 42, espnRank: 44, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 20, gamesPlayed2023: 12, stats2023: { receptions: 59, receivingYards: 737, receivingTds: 5 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { receptions: 75, receivingYards: 900, receivingTds: 6 }, espnPpgProjected: 12.8, sleeperPpgProjected: 13.3, notes: "Puka Nacua's emergence has capped his ceiling significantly.", archetype: "Veteran Possession WR", projectionModifiers: { catalysts: ["Strong rapport with Stafford"], concerns: ["Age and injury history", "No longer the clear #1 WR"] } },
    { id: 35, name: "Mark Andrews", position: P.TE, team: "BAL", byeWeek: 14, tier: 4, adp: 43, espnRank: 42, opportunityShare: 'High', injuryRisk: 'Medium', strengthOfSchedule: 31, gamesPlayed2023: 10, stats2023: { receptions: 45, receivingYards: 544, receivingTds: 6 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { receptions: 70, receivingYards: 850, receivingTds: 7 }, espnPpgProjected: 12.5, sleeperPpgProjected: 13.0, archetype: "Red Zone Threat TE", projectionModifiers: { catalysts: ["Primary red zone target for Lamar"], concerns: ["Returning from major injury", "Toughest schedule for TEs"] } },
    { id: 69, name: "Zay Flowers", position: P.WR, team: "BAL", byeWeek: 14, tier: 4, adp: 44, espnRank: 46, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 30, gamesPlayed2023: 16, stats2023: { receptions: 77, receivingYards: 858, receivingTds: 5, rushingYards: 56, rushingTds: 1 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 80, receivingYards: 900, receivingTds: 5, rushingYards: 50, rushingTds: 1 }, espnPpgProjected: 12.2, sleeperPpgProjected: 12.6, archetype: "YAC Specialist", projectionModifiers: { catalysts: ["Should see natural second-year growth"], concerns: ["Toughest schedule for WRs", "Not the primary red zone target"] } },
    { id: 32, name: "Anthony Richardson", position: P.QB, team: "IND", byeWeek: 14, tier: 4, adp: 45, espnRank: 48, opportunityShare: 'High', injuryRisk: 'High', strengthOfSchedule: 13, gamesPlayed2023: 4, stats2023: { passingYards: 577, passingTds: 3, interceptions: 1, rushingYards: 136, rushingTds: 4 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { passingYards: 3200, passingTds: 18, interceptions: 9, rushingYards: 650, rushingTds: 8 }, espnPpgProjected: 20.5, sleeperPpgProjected: 21.2, notes: "Potential to be the QB1 overall due to rushing, but carries major injury risk.", archetype: "Konami Code QB", projectionModifiers: { catalysts: ["League-winning rushing upside"], concerns: ["Major injury risk", "Inexperienced as a passer"] } },
    { id: 73, name: "Tank Dell", position: P.WR, team: "HOU", byeWeek: 14, tier: 4, adp: 46, espnRank: 49, opportunityShare: 'Medium', injuryRisk: 'High', strengthOfSchedule: 25, gamesPlayed2023: 11, stats2023: { receptions: 47, receivingYards: 709, receivingTds: 7 }, drafted: false, gamesPlayed2024Projected: 15, stats2024Projected: { receptions: 65, receivingYards: 900, receivingTds: 7 }, espnPpgProjected: 12.9, sleeperPpgProjected: 13.4, notes: "Returning from a significant leg injury, and now faces more target competition.", archetype: "Boom/Bust WR2", projectionModifiers: { catalysts: ["Explosive chemistry with Stroud"], concerns: ["Returning from major injury", "Increased target competition"] } },
    { id: 36, name: "Trey McBride", position: P.TE, team: "ARI", byeWeek: 11, tier: 4, adp: 47, espnRank: 45, opportunityShare: 'High', injuryRisk: 'Low', strengthOfSchedule: 10, gamesPlayed2023: 17, stats2023: { receptions: 81, receivingYards: 825, receivingTds: 3 }, drafted: false, gamesPlayed2024Projected: 17, stats2024Projected: { receptions: 85, receivingYards: 850, receivingTds: 4 }, espnPpgProjected: 11.8, sleeperPpgProjected: 12.3, notes: "Became a target monster late last season, but Marvin Harrison Jr. will command targets.", archetype: "Possession TE" },
];

export const UPDATED_PLAYER_DATA_SIMULATION: (Partial<Player> & { id: number })[] = [
    {
        id: 1, // Christian McCaffrey
        adp: 2, // ADP dropped slightly
        notes: "Slightly lowered ADP due to minor camp concerns, but still elite.",
    },
    {
        id: 6, // Breece Hall
        espnRank: 2, // Moved up in ESPN ranks
        stats2024Projected: { rushingYards: 1150, rushingTds: 8, receptions: 85, receivingYards: 700, receivingTds: 5 },
    },
    {
        id: 17, // Justin Jefferson
        sleeperPpgProjected: 19.1, // Increased projection
    },
    {
        id: 23, // Jonathan Taylor
        injuryRisk: 'Medium',
        notes: "Injury risk downgraded from High to Medium after positive camp reports."
    },
    {
        id: 25, // Marvin Harrison Jr.
        adp: 14, // ADP rising
        espnRank: 15,
        espnPpgProjected: 16.8,
    }
];
